### ISSUE TITLE
PSI Edition

### ISSUE THREAD

**Issue by poznas** [supsub/egzamin_kurde#1]
Hi Mordo

How about PSI? it's even more milionerzy'able than SOA

Pozdrawiam

**Comment by poznas** [comment]
@milowedo @KarolGrzesiak @bartlomiejzachariasz @Rudobart

**Comment by supsub** [comment]
Hello @poznas
I'm considering this feature. Keep watching my repository. 
Pozdrawiam,

**Comment by milowedo** [comment]
Hello Juliusz,
that would be great.
Elo,
